### ISSUE TITLE
中文环境中的基线问题

### ISSUE THREAD

**Issue by huangdawei** [junmer/edp-build-iconfont-demo#2]
中文字体的一般没有拉丁文那样的下降部，所以如果生成 icon fonts 时基线高度为 0 的话，icon 相对与中文字体往往偏下，如图：
![down](https://cloud.githubusercontent.com/assets/520542/7637702/736640bc-faa2-11e4-81eb-0e6ecda804e4.png)

如果将基线高度设置为 10%，效果如下：
![up](https://cloud.githubusercontent.com/assets/520542/7637723/8f55146a-faa2-11e4-82eb-aa19b592d304.png)

所以是否可能提供设置基线高度的配置项呢？

**Comment by junmer** [comment]
@huangdawei 赞细节，[fontmin](https://github.com/ecomfe/fontmin) 底层支持，我加一下 option 和 文档
